# Read the documentation at https://github.com/Domplanto/StreamLabsPlugin

streamlabs:
  socket_token: "" # Put your Streamlabs socket token here

affected_players: # Players that will be affected by the actions {player}
  - "domplanto"
  - "codingcat"

show_status_messages: true # Whether the plugin will send status messages in chat (for example "Successfully connected to Streamlabs")

actions:
  example_reward:
    enabled: true # Whether the action is enabled
    action: streamlabs_donation # The action that will trigger it
    conditions: # Conditions that must be met for the action to trigger
      - "{amount}>50"
      - "{amount}<100"
      - "{currency}=USD"
    messages: # Messages that will be sent when the action triggers. USE § FOR COLOR CODES, NOT &!
      - "[message]§l§6{user} §r§9donated {amount_formatted}!"
      - "[title]§cNew Donation!"
      - "[subtitle]§a{user} §9donated {amount_formatted}!"
    commands: # Commands that will be executed when the action triggers. for "Text" use \"Text\"
      - "give {player} diamond {amount}"
      - "effect give {player} regeneration {amount} 1"
      - "[{amount}/10]execute at {player} run summon zombie ~ ~ ~ {CustomName:'[{\"text\":\"{user}\"}]'}" # [{amount}/10] will be replaced with the amount divided by 10

debug_mode: false # DO NOT change this unless you know what you're doing, it will spam your console with detailed information about Streamlabs API events