name: StreamLabs
version: '1.1.1'
main: me.Domplanto.streamLabs.StreamLabs
api-version: '1.21'
author: Domplanto
description: A plugin that integrates Streamlabs events with Minecraft commands

commands:
  streamlabs:
    description: Main command for Streamlabs integration
    usage: /<command> <connect|disconnect|status|reload>
    permission: streamlabs.admin

permissions:
  streamlabs.admin:
    description: Allows access to all Streamlabs commands
    default: op